### ISSUE TITLE
Broken path to wavs in help file examples

### ISSUE THREAD

**Issue by leandroyako** [spluta/BufFFT#1]
Hi, in the help files `PathName(BufFFT.filenameSymbol.asString).pathOnly+/+"sounds/Stairs2.wav"` should point to folder `Sounds` with uppercase s

**Comment by spluta** [comment]
Are you on Linux? This doesn't cause a problem for me on Mac, but you are absolutely correct and I will fix it.

**Comment by leandroyako** [comment]
Sorry, I forgot to add I'm on Linux and it was giving me an error
BTW the examples sounds great!
